services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/app/backend-jo/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: mysql

    env_file:
      - ./.env.dev
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: