# Generated by Django 5.1 on 2024-09-18 12:48

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=50, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('country', models.CharField(max_length=75, verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Lieu')),
                ('image', models.ImageField(upload_to='uploads/locations', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id_offer', models.SmallAutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=10, verbose_name="Nom de l'offre")),
                ('number_of_seats', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de places')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Réduction')),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id_sport', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Sport')),
                ('pictogram', models.ImageField(upload_to='uploads/sports', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backoffice.user')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('password', models.CharField(max_length=50, verbose_name='Mot de passe')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro de téléphone')),
                ('auth_token', models.CharField(max_length=250, unique=True, verbose_name="Clé d'authentification")),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
            bases=('backoffice.user',),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_validation_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.user', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.SmallAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('description', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.location', verbose_name='Lieu')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.sport', verbose_name='Sport')),
            ],
            options={
                'verbose_name': 'Évènement',
                'verbose_name_plural': 'Évènements',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buying_token', models.CharField(max_length=250, unique=True, verbose_name="Clé d'achat")),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.cart', verbose_name='Commande')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.event', verbose_name='Épreuve')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.offer', verbose_name='Offre')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id_user_offer', models.SmallAutoField(primary_key=True, serialize=False)),
                ('child_discount', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Réduction enfant')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.offer', verbose_name='Offre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tarif spécial',
                'verbose_name_plural': 'Tarifs spéciaux',
                'constraints': [models.UniqueConstraint(fields=('user', 'offer'), name='unique_user_offer')],
            },
        ),
    ]
