# Generated by Django 5.1 on 2024-08-08 15:21

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.SmallAutoField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id_offer', models.SmallAutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=10)),
                ('number_of_seats', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backoffice.user')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('auth_token', models.CharField(max_length=250, unique=True)),
            ],
            bases=('backoffice.user',),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id_cart', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_validation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buying_token', models.CharField(max_length=250, unique=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.cart')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.event')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.offer')),
            ],
        ),
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id_user_offer', models.SmallAutoField(primary_key=True, serialize=False)),
                ('is_a_child', models.BooleanField(default=False)),
                ('child_discount', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'offer'), name='unique_user_offer')],
            },
        ),
    ]
