# Generated by Django 5.1 on 2024-09-04 08:42

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Évènement', 'verbose_name_plural': 'Évènements'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offre', 'verbose_name_plural': 'Offres'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='useroffer',
            options={'verbose_name': 'Tarif spécial', 'verbose_name_plural': 'Tarifs spéciaux'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_validation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat"),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.user', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='auth_token',
            field=models.CharField(max_length=250, unique=True, verbose_name="Clé d'authentification"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport_name',
            field=models.CharField(max_length=30, verbose_name='Épreuve'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Réduction'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number_of_seats',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de places'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_name',
            field=models.CharField(max_length=10, verbose_name="Nom de l'offre"),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='buying_token',
            field=models.CharField(max_length=250, unique=True, verbose_name="Clé d'achat"),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.cart', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.event', verbose_name='Épreuve'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.offer', verbose_name='Offre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=75, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='child_discount',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Réduction enfant'),
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='is_a_child',
            field=models.BooleanField(default=False, verbose_name='Est-ce un enfant ?'),
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.offer', verbose_name='Offre'),
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.user', verbose_name='Utilisateur'),
        ),
    ]
