# Generated by Django 5.1 on 2024-10-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id_user_ticket', models.SmallAutoField(primary_key=True, serialize=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.DeleteModel(
            name='UserOffer',
        ),
        migrations.AddConstraint(
            model_name='userticket',
            constraint=models.UniqueConstraint(fields=('user', 'ticket'), name='unique_user_ticket'),
        ),
    ]
