# Generated by Django 5.1.2 on 2024-10-25 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Événement', 'verbose_name_plural': 'Événements'},
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number_of_seats',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de place'),
        ),
        migrations.AlterField(
            model_name='spectatorticket',
            name='spectator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.spectator', verbose_name='Spectateur'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.event', verbose_name='Événement'),
        ),
    ]
