# Generated by Django 5.1 on 2024-09-10 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_alter_cart_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useroffer',
            name='is_a_child',
        ),
        migrations.AlterField(
            model_name='useroffer',
            name='child_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Réduction enfant'),
        ),
    ]
